n = int(input('Digite um número inteiro: '))
n2 = int(input('Digite outro número inteiro: '))
n3 = float(input('Digite um número real: '))
print('O produto do dobro do primeiro com metade do segundo é: {}'.format(n *2 + n2/2))
print('A soma do triplo do primeiro com o terceiro é: {}'.format(n * 3 + n3))
print('O terceiro elevado ao cubo é: {:.2f}'.format(n3 ** 3))
