hora = float(input('Digite o valor da sua hora R$'))
mes = float(input('Digite o valor de horas trabalhadas no mês '))
sal = hora * mes
if sal < 900 and sal > 0:
    des = sal * (13/100)
    print(f'O salário bruto é de {sal}')
    print('O valor do IR é de R$0.00')
    print(f'O valor do INSS é de R${sal * (10/100)}')
    print(f'O valor do FGTS é de R${sal * (11/100)}')
    print(f'O valor do sindicato é de R${sal * (3/100)}')
    print(f'O total de descontos é de R${des}')
    print(f'O salário liquido é de R${sal - des}')
elif sal >= 900:
    des = sal * (18/100)
    print(f'O salário bruto é de {sal}')
    print(f'O valor do IR é de R${sal * (5/100)}')
    print(f'O valor do INSS é de R${sal * (10/100)}')
    print(f'O valor do FGTS é de R${sal * (11/100)}')
    print(f'O valor do sindicato é de R${sal * (3/100)}')
    print(f'O total de descontos é de R${des}')
    print(f'O salário liquido é de R${sal - des}')
elif sal >= 1500:
    des = sal * (23/100)
    print(f'O salário bruto é de {sal}')
    print(f'O valor do IR é de R${sal * (10/100)}')
    print(f'O valor do INSS é de R${sal * (10/100)}')
    print(f'O valor do FGTS é de R${sal * (11/100)}')
    print(f'O valor do sindicato é de R${sal * (3/100)}')
    print(f'O total de descontos é de R${des}')
    print(f'O salário liquido é de R${sal - des}')
elif sal >= 2500:
    des = sal * (33/100)
    print(f'O salário bruto é de {sal}')
    print(f'O valor do IR é de R${sal * (20/100)}')
    print(f'O valor do INSS é de R${sal * (10/100)}')
    print(f'O valor do FGTS é de R${sal * (11/100)}')
    print(f'O valor do sindicato é de R${sal * (3/100)}')
    print(f'O total de descontos é de R${des}')
    print(f'O salário liquido é de R${sal - des}')
else:
    print('Valor INVÁLIDO! ')
