n1 = float(input('Digite a primeira nota: '))
n2 =float(input('Digite o segundo número: '))
n3 = float(input('Digite o terceiro número: '))
n4 = float(input('Digite o quarto número: '))
print('A média da sua nota é {:.1f}'.format((n1 + n2 + n3 + n4)/ 4))
